version: '3'

vars:
  APP_VERSION: '{{.APP_VERSION | default "latest" }}'
  DOCKER_REPOSITORY_PREFIX: '{{.DOCKER_REPOSITORY_PREFIX | default "docker.io/nightmanager"}}'
  BACKEND_ACCESS_TYPE: '{{.BACKEND_ACCESS_TYPE | default "by-path"}}'

tasks:
  set-envs:
    cmds:
      - echo "export LOG_LEVEL=debug"
      - echo "export APP_ENV=development"
  clean:
    cmds:
      - rm dist/*
  setup-npm:
    cmds:
      - mkdir -p .tasks.uptodate
      - npm ci
      - echo > .tasks.uptodate/npmci
    sources:
      - package-lock.json
    generates:
      - .tasks.uptodate/npmci
  build:
    cmds:
      - task: setup-npm
      - npm run dist
    sources:
      - src/**/*
      - package-lock.json
      - .tasks.uptodate/npmci
      - taskfile.yaml
    generates:
      - dist/bundle.js
      - dist/index.html
  docker:
    cmds:
      - task: build
      - |
        if [[ "{{.DOCKER_REPOSITORY_PREFIX}}" = "minikube" ]];
        then
          echo "Targeting minikube..."
          eval $(minikube -p minikube docker-env)
        fi

        cp dist/* deploy/docker/
        docker build -t iconrepo-client:{{.APP_VERSION}} deploy/docker/

        if [[ "{{.DOCKER_REPOSITORY_PREFIX}}" != "minikube" ]];
        then
          docker tag iconrepo-client {{.DOCKER_REPOSITORY_PREFIX}}/iconrepo-client:{{.APP_VERSION}}
          docker push {{.DOCKER_REPOSITORY_PREFIX}}/iconrepo-client:{{.APP_VERSION}}
        fi
  k8s:
    cmds:
      - task: docker
      - |
        set -x
        kubectl create configmap iconrepo-client \
            "--from-file=client-config.json=deploy/backend-access/{{.BACKEND_ACCESS_TYPE}}.json" \
            --dry-run=client -o yaml | \
          kubectl apply -f -
        ICONEPO_CLIENT_IMAGE=iconrepo-client:{{.APP_VERSION}}
        [ "{{.DOCKER_REPOSITORY_PREFIX}}" != "minikube" ] && export ICONEPO_CLIENT_IMAGE={{.DOCKER_REPOSITORY_PREFIX}}/$ICONEPO_CLIENT_IMAGE
        envsubst < deploy/k8s/client.template.yaml > deploy/k8s/client.yaml
        kubectl apply -f deploy/k8s/client.yaml
